// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYuy0LIt_E9QhrC0Dh_PU-Dh_QzzInUoE',
    appId: '1:307615014332:web:123b8b236bf2691fc19fb9',
    messagingSenderId: '307615014332',
    projectId: 'neko-money-manager',
    authDomain: 'neko-money-manager.firebaseapp.com',
    storageBucket: 'neko-money-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXLoJUJG75Ss9gWARLC_nMlKepR0WWn8',
    appId: '1:307615014332:android:b9e79de552e43f45c19fb9',
    messagingSenderId: '307615014332',
    projectId: 'neko-money-manager',
    storageBucket: 'neko-money-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf40Wq4z8JSPBLNujjEuRsRRU8HmAKj50',
    appId: '1:307615014332:ios:f06d91b1e9e8312bc19fb9',
    messagingSenderId: '307615014332',
    projectId: 'neko-money-manager',
    storageBucket: 'neko-money-manager.firebasestorage.app',
    iosBundleId: 'com.neko.manager.nekoMoneyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf40Wq4z8JSPBLNujjEuRsRRU8HmAKj50',
    appId: '1:307615014332:ios:f06d91b1e9e8312bc19fb9',
    messagingSenderId: '307615014332',
    projectId: 'neko-money-manager',
    storageBucket: 'neko-money-manager.firebasestorage.app',
    iosBundleId: 'com.neko.manager.nekoMoneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYuy0LIt_E9QhrC0Dh_PU-Dh_QzzInUoE',
    appId: '1:307615014332:web:798c6fbbfaf23d0bc19fb9',
    messagingSenderId: '307615014332',
    projectId: 'neko-money-manager',
    authDomain: 'neko-money-manager.firebaseapp.com',
    storageBucket: 'neko-money-manager.firebasestorage.app',
  );
}
